### ISSUE TITLE
Padding emojis don't pad well

### ISSUE THREAD

**Issue by disq** [keith-turner/ecoji#12]
Padding emojis are not soft things (how is ☕️ or ⚜️soft? on the contrary!)

Maybe use  🛏 and/or ☁️for padding.

**Comment by ctubbsii** [comment]
I think there's a restriction on the padding... it kinda needs to be carefully selected to preserve sort order.

**Comment by keith-turner** [comment]
Thanks for the suggestion, but the characters are frozen now that 1.0.0 is tagged.  I would have taken those choices instead of the pokey padding.  At the time I chose those I Was just looking for things that made the sort order work out.
