### ISSUE TITLE
Wrapping option always places four emojis at once

### ISSUE THREAD

**Issue by Rayne** [keith-turner/ecoji#17]
I discovered while writing the CLI interface for [ecoji-php](https://github.com/Rayne/ecoji-php) that the wrapping option doesn't produce the expected results. It always places groups of four emojis.

**Example**

```bash
echo -n "Hello World" | ecoji -w 1
```

**Expected Result**

```
🏯
🔩
🚗
🌷
🍉
👇
🦒
🕊
👡
☕
☕
☕
```

**Actual Result**

```bash
🏯🔩🚗🌷
🍉👇🦒🕊
👡☕☕☕
```

**Comment by keith-turner** [comment]
I can fix this with a Writer that wraps the Writer and outputs newlines every Nth rune
